//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OriginalWorldProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Message()
        {
            this.M_moodsheet = new HashSet<M_moodsheet>();
            this.Report_table = new HashSet<Report_table>();
            this.Rta_message = new HashSet<Rta_message>();
        }
    
        public int Messagenumber { get; set; }
        public string Msg_Content { get; set; }
        public System.DateTime Messagetime { get; set; }
        public string MemberID { get; set; }
        public int WorksContentID { get; set; }
        public string Status_ID { get; set; }
        public bool Not_spoiler { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_moodsheet> M_moodsheet { get; set; }
        public virtual Member Member { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report_table> Report_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rta_message> Rta_message { get; set; }
        public virtual Works_Content Works_Content { get; set; }
    }
}
