//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OriginalWorldProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_table
    {
        public int Report_event_ID { get; set; }
        public string Content { get; set; }
        public System.DateTime Report_time { get; set; }
        public string Processing_status_ID { get; set; }
        public string Processing_method_ID { get; set; }
        public string Administrator_ID { get; set; }
        public string Report_category_ID { get; set; }
        public string Report_datail_ID { get; set; }
        public string MemberID { get; set; }
        public string WorksID { get; set; }
        public string WriterhomeID { get; set; }
        public string WriterID { get; set; }
        public Nullable<int> Messagenumber { get; set; }
        public Nullable<int> WorksContentID { get; set; }
        public Nullable<int> RtamessageID { get; set; }
    
        public virtual Administrator Administrator { get; set; }
        public virtual Member Member { get; set; }
        public virtual Message Message { get; set; }
        public virtual Processing_method Processing_method { get; set; }
        public virtual Processing_status_table Processing_status_table { get; set; }
        public virtual Report_category Report_category { get; set; }
        public virtual Report_datail Report_datail { get; set; }
        public virtual Works Works { get; set; }
        public virtual Writer_home Writer_home { get; set; }
        public virtual Writer Writer { get; set; }
        public virtual Works_Content Works_Content { get; set; }
        public virtual Rta_message Rta_message { get; set; }
    }
}
