//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OriginalWorldProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rta_message
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rta_message()
        {
            this.Re_message = new HashSet<Re_message>();
            this.Report_table = new HashSet<Report_table>();
        }
    
        public int RtamessageID { get; set; }
        public string Rta_msg_Content { get; set; }
        public System.DateTime Rtatime { get; set; }
        public int Messagenumber { get; set; }
        public string MemberID { get; set; }
        public string Status_ID { get; set; }
        public bool Not_spoiler { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Message Message { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Re_message> Re_message { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report_table> Report_table { get; set; }
        public virtual Status Status { get; set; }
    }
}
